language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository

script:
 - ./gradlew clean build -PdisablePreDex --continue --stacktrace

branches:
  only:
    - master
    - develop